### ISSUE TITLE
npm Error

### ISSUE THREAD

**Issue by renepetermann289** [PHT-Medic/desktop-app#356]
Hallo zusammen, ich habe ein Problem beim Installieren der `desktop-app`. 
Fehler:
    
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! desktop-app@2.0.3 postinstall: `electron-builder install-app-deps`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the desktop-app@2.0.3 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Versionen:
    
    - node v10.19.0
    - npm v6.14.4

Ich habe das Repo lokal geladen und im Ordner `npm install` ausgeführt.

Hat jemand eine Idee, was der Grund sein kann?

**Comment by tada5hi** [comment]
@renepetermann289 ich vermute, dass deine NodeJs Version ist zu alt. 
Versuche mal ob die Installation mit v16.x funktioniert.

**Comment by renepetermann289** [comment]
Das hat geklappt super vielen dankt!
Jetzt habe ich mit dem rpm rum build nur ein weiteres Problem:

    ERROR  Cannot read properties of undefined (reading 'hook')                                                                    4:33:51 PM

      at nuxtBootstrapVue (node_modules/bootstrap-vue/nuxt/index.js:34:13)
      at installModule (node_modules/@nuxt/kit/dist/index.mjs:2409:101)
      at async initNuxt (node_modules/nuxt/dist/index.mjs:3237:7)
      at async loadNuxt (node_modules/nuxt/dist/index.mjs:3310:5)
      at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
      at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:38:18)
      at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:36:5)
      at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

    vitron build

    Build application for production.

    Options:
      -h, --help     Show help                                             [boolean]
      -r, --root     Path to your project root directory.
                                              [default: "/Users/username/desktop-app"]
      -f, --flags    Specify platform(s) and architecture(s) to build the
                     application for.
            [array] [choices: "all", "mac", "win", "linux", "ia32", "x64", "armv7l",
                                                              "arm64"] [default: []]
      -c, --config   Name of the electron-builder configuration file.
                                                   [default: "electron-builder.yml"]
      -v, --version  Show version number                                   [boolean]

    [Error: ENOENT: no such file or directory, lstat '/Users/username/desktop-app/src/renderer/dist'] {
      errno: -2,
      code: 'ENOENT',
      syscall: 'lstat',
      path: '/Users/username/desktop-app/src/renderer/dist'

**Comment by tada5hi** [comment]
> Das hat geklappt super vielen dankt!
> 
> Jetzt habe ich mit dem rpm rum build nur ein weiteres Problem:
> 
> 
> 
> Nuxt version (npm ls): nuxt@3.6.3
> 
> 
> 
>     ERROR  Cannot read properties of undefined (reading 'hook')                                                                    4:33:51 PM
> 
> 
> 
>       at nuxtBootstrapVue (node_modules/bootstrap-vue/nuxt/index.js:34:13)
> 
>       at installModule (node_modules/@nuxt/kit/dist/index.mjs:2409:101)
> 
>       at async initNuxt (node_modules/nuxt/dist/index.mjs:3237:7)
> 
>       at async loadNuxt (node_modules/nuxt/dist/index.mjs:3310:5)
> 
>       at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2537:19)
> 
>       at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:38:18)
> 
>       at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:36:5)
> 
>       at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
> 
> 
> 
>     vitron build
> 
> 
> 
>     Build application for production.
> 
> 
> 
>     Options:
> 
>       -h, --help     Show help                                             [boolean]
> 
>       -r, --root     Path to your project root directory.
> 
>                                               [default: "/Users/username/desktop-app"]
> 
>       -f, --flags    Specify platform(s) and architecture(s) to build the
> 
>                      application for.
> 
>             [array] [choices: "all", "mac", "win", "linux", "ia32", "x64", "armv7l",
> 
>                                                               "arm64"] [default: []]
> 
>       -c, --config   Name of the electron-builder configuration file.
> 
>                                                    [default: "electron-builder.yml"]
> 
>       -v, --version  Show version number                                   [boolean]
> 
> 
> 
>     [Error: ENOENT: no such file or directory, lstat '/Users/username/desktop-app/src/renderer/dist'] {
> 
>       errno: -2,
> 
>       code: 'ENOENT',
> 
>       syscall: 'lstat',
> 
>       path: '/Users/username/desktop-app/src/renderer/dist'

Da hast du die nuxt Version aber manuell geupgraded oder ? 
Aktuell ist diese im repo noch bei 2.16.1
